# Generated by Django 5.1.1 on 2024-09-15 18:50

import django.db.models.deletion
import django.utils.timezone
import saloonfinance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('saloonfinance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Purchase price')),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1.0, max_digits=10, verbose_name='Exchange rate')),
                ('purchase_price_in_default_currency', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Purchase price in default currency')),
                ('purchase_date', models.DateField(default=django.utils.timezone.now, verbose_name='Purchase date')),
                ('supplier', models.CharField(blank=True, max_length=255, verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Item Purchase',
                'verbose_name_plural': 'Item Purchases',
            },
        ),
        migrations.CreateModel(
            name='ItemUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
            ],
            options={
                'verbose_name': 'Item Used',
                'verbose_name_plural': 'Items Used',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Price')),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1.0, max_digits=10, verbose_name='Exchange rate')),
                ('amount_in_default_currency', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Amount in default currency')),
                ('current_stock', models.PositiveIntegerField(default=0, verbose_name='Current stock')),
                ('currency', models.ForeignKey(default=saloonfinance.models.Currency.get_default, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='saloonfinance.currency', verbose_name='Currency')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
    ]
