# Generated by Django 5.1.1 on 2024-09-15 18:50

import django.db.models.deletion
import saloonfinance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('saloon', '0003_remove_barber_permissions_and_more'),
        ('saloonfinance', '0001_initial'),
        ('salooninventory', '0001_initial'),
        ('saloonservices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_purpose',
            field=models.ManyToManyField(related_name='items', to='saloonservices.hairstyle', verbose_name='Item purpose'),
        ),
        migrations.AddField(
            model_name='item',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='saloon.salon', verbose_name='Salon'),
        ),
        migrations.AddField(
            model_name='itempurchase',
            name='cashregister',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='saloonfinance.cashregister', verbose_name='Cash Register'),
        ),
        migrations.AddField(
            model_name='itempurchase',
            name='currency',
            field=models.ForeignKey(default=saloonfinance.models.Currency.get_default, on_delete=django.db.models.deletion.PROTECT, to='saloonfinance.currency', verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='itempurchase',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='salooninventory.item', verbose_name='Item'),
        ),
        migrations.AddField(
            model_name='itempurchase',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_purchases', to='saloon.salon', verbose_name='Salon'),
        ),
        migrations.AddField(
            model_name='itemused',
            name='barber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saloon.barber', verbose_name='Barber'),
        ),
        migrations.AddField(
            model_name='itemused',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uses', to='salooninventory.item', verbose_name='Item'),
        ),
        migrations.AddField(
            model_name='itemused',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_used', to='saloon.salon', verbose_name='Salon'),
        ),
        migrations.AddField(
            model_name='itemused',
            name='shave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_used', to='saloonservices.shave', verbose_name='Shave'),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('name', 'salon')},
        ),
        migrations.AlterUniqueTogether(
            name='itemused',
            unique_together={('item', 'shave', 'salon')},
        ),
    ]
