# Generated by Django 5.1.1 on 2024-09-15 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saloon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbertype',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barber_types', to='saloon.salon', verbose_name='Salon'),
        ),
    ]
