# Generated by Django 5.1.1 on 2024-09-15 18:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saloon', '0002_alter_barbertype_salon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barber',
            name='permissions',
        ),
        migrations.AddIndex(
            model_name='barber',
            index=models.Index(fields=['is_active'], name='saloon_barb_is_acti_3fe24d_idx'),
        ),
        migrations.AddIndex(
            model_name='barber',
            index=models.Index(fields=['start_date', 'end_date'], name='saloon_barb_start_d_99be47_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['name'], name='saloon_clie_name_aa73dc_idx'),
        ),
        migrations.AddIndex(
            model_name='salon',
            index=models.Index(fields=['name'], name='saloon_salo_name_0841c9_idx'),
        ),
        migrations.AddIndex(
            model_name='salon',
            index=models.Index(fields=['is_active'], name='saloon_salo_is_acti_a06101_idx'),
        ),
        migrations.DeleteModel(
            name='BarberPermission',
        ),
    ]
