# Generated by Django 5.1.1 on 2024-09-15 15:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ('-date_joined',), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphabets characters are allowed.')], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphabets characters are allowed.')], verbose_name='last name'),
        ),
    ]
